name: 'Chromatic Publish'

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  build:
    if: ${{ github.event.label.name == 'chromatic' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checking out project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install --ignore-scripts
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            _**🤖 Beep boop, here's your Chromatic url: ${{ steps.chromatic.outputs.storybookUrl }}**_
          comment_tag: 🤖 Beep boop
